#!/bin/bash -l
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:05:00

# not needed in real script, this is only to localize test
cd $PBS_O_WORKDIR
PATH="../bin:$PATH"

# log start of work item execution
alog --state start

# define work item parameters
source <(aenv --data data.csv)

# do actual work, i.e., original PBS script
cd $PBS_O_WORKDIR
echo "alpha = $alpha"
echo "beta = $beta"
echo "gamma = $gamma"
exit_code=$(( $RANDOM % 2 ))

result=$(( $alpha + $beta + $gamma ))
echo "$alpha,$beta,$gamma,$result" > "out-${PBS_ARRAYID}.txt"

# log end of work item execution
alog --state end --exit "$exit_code"
