site_name: atools (Job array tools) documentation
site_description: atools is a set of utilities for using job arrays in a very convenient way.
site_author: Geert Jan Bex
nav:
- Introduction and motivation: 'index.md'
- What are job arrays?: 'job_arrays.md'
- Getting your parameters: 'aenv.md'
- Logging for fun and profit: 'alog.md'
- Automatically adapting your job script: 'acreate.md'
- Monitoring jobs and resuming tasks: 'arange.md'
- Gathering output: 'areduce.md'
- Detailed job statistics: 'aload.md'
- Installation: 'install.md'
- FAQ: 'faq.md'
- Configuration file: 'config.md'
- Change log: 'changes.md'
- Contact and support: 'contact.md'
site_dir: html_docs/atools
theme: readthedocs
